# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'export.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Export(object):
    def setupUi(self, Export):
        Export.setObjectName("Export")
        Export.resize(612, 161)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Export)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Export)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_expr = QtWidgets.QComboBox(Export)
        self.comboBox_expr.setObjectName("comboBox_expr")
        self.comboBox_expr.addItem("")
        self.comboBox_expr.addItem("")
        self.comboBox_expr.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_expr)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Export)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_filepath = QtWidgets.QLineEdit(Export)
        self.lineEdit_filepath.setObjectName("lineEdit_filepath")
        self.horizontalLayout_2.addWidget(self.lineEdit_filepath)
        self.pushButton_select_filepath = QtWidgets.QPushButton(Export)
        self.pushButton_select_filepath.setObjectName("pushButton_select_filepath")
        self.horizontalLayout_2.addWidget(self.pushButton_select_filepath)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Export)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(Export)
        self.buttonBox.accepted.connect(Export.accept) # type: ignore
        self.buttonBox.rejected.connect(Export.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Export)

    def retranslateUi(self, Export):
        _translate = QtCore.QCoreApplication.translate
        Export.setWindowTitle(_translate("Export", "Dialog"))
        self.label.setText(_translate("Export", "导出的实验"))
        self.comboBox_expr.setItemText(0, _translate("Export", "海绵单体"))
        self.comboBox_expr.setItemText(1, _translate("Export", "面源斑块"))
        self.comboBox_expr.setItemText(2, _translate("Export", "海绵地块"))
        self.label_2.setText(_translate("Export", "导出路径"))
        self.pushButton_select_filepath.setText(_translate("Export", "选择路径"))
