# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sim_dates.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SimDates(object):
    def setupUi(self, SimDates):
        SimDates.setObjectName("SimDates")
        SimDates.resize(260, 200)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(SimDates)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_sim_start_datetime = QtWidgets.QLabel(SimDates)
        self.label_sim_start_datetime.setObjectName("label_sim_start_datetime")
        self.horizontalLayout_3.addWidget(self.label_sim_start_datetime)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_sim_end_datetime = QtWidgets.QLabel(SimDates)
        self.label_sim_end_datetime.setObjectName("label_sim_end_datetime")
        self.horizontalLayout_2.addWidget(self.label_sim_end_datetime)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_sim_timestep = QtWidgets.QLabel(SimDates)
        self.label_sim_timestep.setObjectName("label_sim_timestep")
        self.verticalLayout_2.addWidget(self.label_sim_timestep)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.dateTime_start_edit = QtWidgets.QDateTimeEdit(SimDates)
        self.dateTime_start_edit.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 5, 25), QtCore.QTime(10, 0, 0)))
        self.dateTime_start_edit.setObjectName("dateTime_start_edit")
        self.verticalLayout.addWidget(self.dateTime_start_edit)
        self.dateTime_end_edit = QtWidgets.QDateTimeEdit(SimDates)
        self.dateTime_end_edit.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 5, 25), QtCore.QTime(23, 0, 0)))
        self.dateTime_end_edit.setDate(QtCore.QDate(2021, 5, 25))
        self.dateTime_end_edit.setObjectName("dateTime_end_edit")
        self.verticalLayout.addWidget(self.dateTime_end_edit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinBox_timestep = QtWidgets.QSpinBox(SimDates)
        self.spinBox_timestep.setMinimum(1)
        self.spinBox_timestep.setProperty("value", 60)
        self.spinBox_timestep.setObjectName("spinBox_timestep")
        self.horizontalLayout.addWidget(self.spinBox_timestep)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.buttonBox = QtWidgets.QDialogButtonBox(SimDates)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)

        self.retranslateUi(SimDates)
        self.buttonBox.accepted.connect(SimDates.accept) # type: ignore
        self.buttonBox.rejected.connect(SimDates.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SimDates)

    def retranslateUi(self, SimDates):
        _translate = QtCore.QCoreApplication.translate
        SimDates.setWindowTitle(_translate("SimDates", "仿真日期"))
        self.label_sim_start_datetime.setText(_translate("SimDates", "开始时间"))
        self.label_sim_end_datetime.setText(_translate("SimDates", "结束时间"))
        self.label_sim_timestep.setText(_translate("SimDates", "时间步长（min）"))
        self.dateTime_start_edit.setDisplayFormat(_translate("SimDates", "yyyy/MM/dd H:mm"))
        self.dateTime_end_edit.setDisplayFormat(_translate("SimDates", "yyyy/MM/dd H:mm"))
